Bootstrap: docker
From: gcfntnu/python-base-conda:4.8.2


%environment
    JUP_PORT=8888
    JUP_IPNAME=localhost
    JUP_NOTEBOOK_DIR=$HOME
    JUP_CONFIG="/opt/conda/etc/jupyter/jupyter_notebook_config.py"
    DEBIAN_FRONTEND=noninteractive
    export JUP_PORT JUP_IPNAME JUP_NOTEBOOK_DIR JUP_CONFIG DEBIAN_FRONTEND

    . /opt/conda/etc/profile.d/conda.sh
    conda activate /opt/conda

%post
  export PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

  # update conda
  mamba update --all --yes --quiet

  # install python packages with mamba
  mamba install --quiet --yes \
    anndata \
    anndata2ri \
    bbknn \
    bioservices \
    cellrank \
    cmake \
    cython \
    gsl \
    h5py \
    ipykernel \
    joblib \
    jupyter_nbextensions_configurator \
    jupyterlab \
    leidenalg \
    loompy \
    louvain \
    matplotlib \
    mscorefonts \
    nodejs \
    numba \
    numexpr \
    openpyxl \
    pandas \
    pip \
    pybedtools \
    pybiomart \
    pypairs \
    pytables \
    python-igraph \
    rpy2 \
    scanpy \
    scikit-learn \
    scipy \
    scrublet \
    scvi \
    seaborn \
    statsmodels \
    xlrd \
    xlwt \
    zlib

  # install R packacges with mamba
  mamba install --quiet --yes \
    bioconductor-annotationhub \
    bioconductor-biomart \
    bioconductor-clusterexperiment \
    bioconductor-complexheatmap \
    bioconductor-deseq2 \
    bioconductor-dropletutils \
    bioconductor-hsmmsinglecell \
    bioconductor-mast \
    bioconductor-monocle \
    bioconductor-scater \
    bioconductor-scran \
    bioconductor-slingshot \
    r-argparse \
    r-base=4.0.3 \
    r-biocmanager \
    r-data.table \
    r-devtools \
    r-dplyr \
    r-enrichr \
    r-essentials \
    r-factoextra \
    r-future \
    r-gam \
    r-ggplot2 \
    r-ggpubr \
    r-ggsci \
    r-ggsignif \
    r-hmisc \
    r-irkernel \
    r-knitr \
    r-magrittr \
    r-matrix \
    r-monocle3 \
    r-openxlsx \
    r-pheatmap \
    r-purrr \
    r-usethis \
    r-r.utils \
    r-rcolorbrewer \
    r-readr \
    r-reticulate \
    r-rgl \
    r-seurat \
    r-tidyr \
    r-tidyverse \
    r-upsetr \
    r-venndiagram \
    r-xlsx

  # cerebroApp dependencies
  mamba install --quiet --yes \
    bioconductor-gseabase  \
    bioconductor-gsva \
    bioconductor-qvalue \
    r-colourpicker \
    r-msigdbr \
    r-shinycssloaders \
    r-shinydashboard \
    r-shinyfiles \
    r-shinyjs \
    r-shinywidgets

  # clean conda cache
  mamba clean -ai

  # pip
  pip --no-cache-dir install -U \
    fa2 \
    FlowKit \
    gprofiler-official \
    magic-impute && \
  pip install --no-cache-dir git+https://github.com/theislab/scachepy && \
  pip install --no-cache-dir git+https://github.com/DmitryUlyanov/Multicore-TSNE.git && \
  pip install --no-cache-dir git+https://github.com/theislab/diffxpy

  # jupyterlab extensions
  jupyter labextension install "@jupyterlab/toc"
  # download jupyter config
  wget https://raw.githubusercontent.com/dcgc-bfx/dcgc-single-cell/main/single_cell/jupyter_notebook_config.json \
      --directory-prefix=/opt/conda/etc/jupyter/

  # rstudio server
  apt-get update && apt-get install -y gdebi-core uuid
  wget https://download2.rstudio.org/server/bionic/amd64/rstudio-server-1.3.1093-amd64.deb
  gdebi -n rstudio-server-1.3.1093-amd64.deb
  rm rstudio-server-1.3.1093-amd64.deb
  apt-get clean
  rm -rf /var/lib/apt/lists/*

  # for running rstudio server with conda R
  git clone https://github.com/grst/rstudio-server-conda.git

  # install R dependencies not available from conda
  R -e "devtools::install_github(repo = 'yanlinlin82/ggvenn')"
  R -e 'BiocManager::install(c(
    "romanhaa/cerebroApp"),
    ask = FALSE, update = FALSE)'

  R -e "devtools::install_github(repo = 'cboettig/knitcitations')"
  R -e 'install.packages(c(
        "PoiClaClu",
        "hutils",
        "singleCellHaystack"), repos="http://cran.r-project.org")'

  chown -R root:users /opt
  chmod -R g+w /opt

%startscript
  # rstudio
  exec /rstudio-server-conda/start_rstudio_server.sh 8787 &

  #jupyter
  PORT=""
  if [ -n "$JUP_PORT" ]; then
  PORT="--port=${JUP_PORT}"
  fi

  IPNAME=""
  if [ -n "$JUP_IPNAME" ]; then
  IPNAME="--ip=${JUP_IPNAME}"
  fi

  NOTEBOOK_DIR=""
  if [ -n "$JUP_NOTEBOOK_DIR" ]; then
  NOTEBOOK_DIR="--notebook-dir=${JUP_NOTEBOOK_DIR}"
  fi

  CONFIG=""
  if [ -n "$JUP_CONFIG" ]; then
  CONFIG="--config=${JUP_CONFIG}"
  fi

  exec jupyter lab --allow-root ${PORT} ${IPNAME} ${NOTEBOOK_DIR} \
    ${CONFIG} --no-browser

%runscript
  # rstudio
  exec /rstudio-server-conda/start_rstudio_server.sh 8787 &

  #jupyter
  PORT=""
  if [ -n "$JUP_PORT" ]; then
  PORT="--port=${JUP_PORT}"
  fi

  IPNAME=""
  if [ -n "$JUP_IPNAME" ]; then
  IPNAME="--ip=${JUP_IPNAME}"
  fi
  
  NOTEBOOK_DIR=""
  if [ -n "$JUP_NOTEBOOK_DIR" ]; then
  NOTEBOOK_DIR="--notebook-dir=${JUP_NOTEBOOK_DIR}"
  fi

  CONFIG=""
  if [ -n "$JUP_CONFIG" ]; then
  CONFIG="--config=${JUP_CONFIG}"
  fi

  exec jupyter lab --allow-root ${PORT} ${IPNAME} ${NOTEBOOK_DIR} \
    ${CONFIG} --no-browser
