Bootstrap: docker
From: gcfntnu/python-base-conda:4.8.2

%help
  Start jupyter lab:
    singularity run --writable-tmpfs --app jupyter library://fabianrost84/dcgc/single-cell.sif

  Start rstudio server:
    singularity run --writable-tmpfs --app rstudio-server library://fabianrost84/dcgc/single-cell.sif 8787

%environment
  DEBIAN_FRONTEND=noninteractive

%post
  export PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

  # update conda
  # mamba update --all --yes --quiet

  # install python packages with mamba
  mamba install --quiet --yes \
    anndata \
    anndata2ri \
    bbknn \
    bioservices \
    cellrank \
    cython \
    gsl \
    h5py \
    ipykernel \
    joblib \
    jupyter_nbextensions_configurator \
    jupyterlab \
    leidenalg \
    libtiff=4.1 `# version 4.2 breaks plotting` \
    loompy \
    louvain \
    nodejs \
    pybedtools \
    pybiomart \
    pypairs \
    pytables \
    python-igraph \
    scanpy \
    scikit-learn \
    scrublet \
    scvi \
    statsmodels \
    xlrd \
    xlwt \
    `# R packages` \
    bioconductor-annotationhub \
    bioconductor-biomart \
    bioconductor-clusterexperiment \
    bioconductor-complexheatmap \
    bioconductor-deseq2 \
    bioconductor-dropletutils \
    bioconductor-hsmmsinglecell \
    bioconductor-loomexperiment \
    bioconductor-mast \
    bioconductor-monocle \
    bioconductor-scater \
    bioconductor-scran \
    bioconductor-slingshot \
    r-argparse \
    r-biocmanager \
    r-kableextra \
    r-enrichr \
    r-factoextra \
    r-future \
    r-gam \
    r-irkernel \
    r-loomr \
    r-monocle3 \
    r-openxlsx \
    r-pheatmap \
    r-readr \
    r-rgl \
    r-sctransform \
    r-seurat=4 \
    r-upsetr \
    r-venndiagram \
    `# cerebro app deps` \
    bioconductor-gseabase  \
    bioconductor-gsva \
    bioconductor-qvalue \
    r-colourpicker \
    r-msigdbr \
    r-shinycssloaders \
    r-shinydashboard \
    r-shinyfiles \
    r-shinyjs \
    r-shinywidgets

  # clean conda cache
  mamba clean -ai

  # pip
  pip --no-cache-dir install -U \
    fa2 \
    FlowKit \
    gprofiler-official \
    magic-impute
  pip install --no-cache-dir git+https://github.com/theislab/diffxpy
  pip install --no-cache-dir git+https://github.com/DmitryUlyanov/Multicore-TSNE.git
  pip install --no-cache-dir git+https://github.com/theislab/scachepy
  pip install --no-cache-dir git+https://github.com/calico/solo.git

  # jupyterlab extensions
  jupyter labextension install "@jupyterlab/toc"
  # download jupyter config
  wget https://raw.githubusercontent.com/dcgc-bfx/dcgc-single-cell/main/single_cell/jupyter_notebook_config.json \
      --directory-prefix=/opt/conda/etc/jupyter/

  # rstudio server
  apt-get update
  apt-get install -y \
    gdebi-core \
    uuid

  wget https://download2.rstudio.org/server/bionic/amd64/rstudio-server-1.3.1093-amd64.deb
  gdebi -n rstudio-server-1.3.1093-amd64.deb
  rm rstudio-server-1.3.1093-amd64.deb

  apt-get clean
  rm -rf /var/lib/apt/lists/*

  # for running rstudio server with conda R
  git clone https://github.com/grst/rstudio-server-conda.git

  # install R dependencies not available from conda
  R -e "devtools::install_github(repo = 'yanlinlin82/ggvenn')"
  R -e 'devtools::install_github("cellgeni/sceasy")'
  R -e 'BiocManager::install(c(
    "romanhaa/cerebroApp"),
    ask = FALSE, update = FALSE)'

  R -e "devtools::install_github(repo = 'cboettig/knitcitations')"
  R -e 'install.packages(c(
        "PoiClaClu",
        "hutils",
        "singleCellHaystack"), repos="http://cran.r-project.org")'

  chmod -R a+w /opt


####################
## rstudio server ##
####################

%apprun rstudio-server
  conda run --no-capture-output -p /opt/conda /rstudio-server-conda/start_rstudio_server.sh "${@}"

#################
## jupyter lab ##
#################

%apprun jupyter
  jupyter lab --no-browser "${@}"
