name: Build and Push
on:
  push:
    branches:
      - main
jobs:

  buildandpush:
    name: Build and Push
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        singularity_version:
          - '3.4.2'
    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged
    steps:
    - name: Check out code for the container build
      uses: actions/checkout@v2

    - name: Build Container
      run: |
        cd single_cell
        singularity build single_cell.sif Singularity

    - name: Push Container
      env:
        SYLABS_TOKEN: ${{secrets.SYLABS_TOKEN}}
      run: |
        echo "$SYLABS_TOKEN" > sylabs-token
        singularity remote login --tokenfile sylabs-token
        singularity build --remote -d library://fabianrost84/dcgc/dcgc-single-cell.sif Singularity
